<a href="https://colab.research.google.com/github/shaukathussain/FrancisCholetgroupStudy/blob/main/7_1_5Weigths_sharing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Weight sharing

In [1]:
from keras import layers
from keras import Input
from keras.models import Model
lstm = layers.LSTM(32)


In [2]:
left_input = Input(shape=(None, 128))
left_output = lstm(left_input)


In [3]:
lstm.weights

[<tf.Variable 'lstm/lstm_cell/kernel:0' shape=(128, 128) dtype=float32, numpy=
 array([[-0.1183266 , -0.07939953,  0.00580449, ...,  0.00557041,
         -0.1272247 , -0.00202988],
        [-0.12814508, -0.06528915,  0.00158726, ...,  0.0269413 ,
          0.05626015,  0.13930814],
        [-0.04165857,  0.04880856,  0.10895239, ..., -0.1496914 ,
          0.10612933,  0.06445278],
        ...,
        [-0.097482  ,  0.07917078, -0.03280744, ..., -0.01616132,
         -0.09346092,  0.02327561],
        [ 0.13444246, -0.05563962,  0.0610376 , ..., -0.14896534,
          0.09293692,  0.04994628],
        [-0.08169919,  0.06360354, -0.06577253, ..., -0.0668468 ,
          0.06853628,  0.0573678 ]], dtype=float32)>,
 <tf.Variable 'lstm/lstm_cell/recurrent_kernel:0' shape=(32, 128) dtype=float32, numpy=
 array([[ 0.08321691, -0.12250945,  0.04466104, ...,  0.09461897,
          0.16784719, -0.0098683 ],
        [-0.14203066, -0.03527103,  0.0101143 , ...,  0.06292138,
         -0.04997117, 

In [4]:
right_input = Input(shape=(None, 128))
right_output = lstm(right_input)

In [5]:
lstm.weights

[<tf.Variable 'lstm/lstm_cell/kernel:0' shape=(128, 128) dtype=float32, numpy=
 array([[-0.1183266 , -0.07939953,  0.00580449, ...,  0.00557041,
         -0.1272247 , -0.00202988],
        [-0.12814508, -0.06528915,  0.00158726, ...,  0.0269413 ,
          0.05626015,  0.13930814],
        [-0.04165857,  0.04880856,  0.10895239, ..., -0.1496914 ,
          0.10612933,  0.06445278],
        ...,
        [-0.097482  ,  0.07917078, -0.03280744, ..., -0.01616132,
         -0.09346092,  0.02327561],
        [ 0.13444246, -0.05563962,  0.0610376 , ..., -0.14896534,
          0.09293692,  0.04994628],
        [-0.08169919,  0.06360354, -0.06577253, ..., -0.0668468 ,
          0.06853628,  0.0573678 ]], dtype=float32)>,
 <tf.Variable 'lstm/lstm_cell/recurrent_kernel:0' shape=(32, 128) dtype=float32, numpy=
 array([[ 0.08321691, -0.12250945,  0.04466104, ...,  0.09461897,
          0.16784719, -0.0098683 ],
        [-0.14203066, -0.03527103,  0.0101143 , ...,  0.06292138,
         -0.04997117, 

In [6]:
merged = layers.concatenate([left_output, right_output], axis=-1)
predictions = layers.Dense(1, activation='sigmoid')(merged)
model = Model([left_input, right_input], predictions)
model.fit([left_data, right_data], targets) ## because we do not have a problem at hand , so there is no left_data and right_data, it will throw error

NameError: ignored

# 7.1.6 Model as layers

In [19]:
from keras import layers
from tensorflow.keras import applications
from keras import Input
xception_base = applications.Xception(weights=None,include_top=False)
left_input = Input(shape=(1080, 1080, 3))
right_input = Input(shape=(1080, 1080, 3))
left_features = xception_base(left_input)
right_input = xception_base(right_input)



In [18]:
xception_base.summary()

Model: "xception"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, None, None,  0           []                               
                                 3)]                                                              
                                                                                                  
 block1_conv1 (Conv2D)          (None, None, None,   864         ['input_3[0][0]']                
                                32)                                                               
                                                                                                  
 block1_conv1_bn (BatchNormaliz  (None, None, None,   128        ['block1_conv1[0][0]']           
 ation)                         32)                                                        

In [11]:
merged_features = layers.concatenate([left_features, right_input], axis=-1)

In [22]:
left_features.shape

TensorShape([None, 34, 34, 2048])

In [21]:
right_input.shape

TensorShape([None, 34, 34, 2048])

In [12]:
merged_features.shape

TensorShape([None, 8, 8, 4096])